services:
  backend:
    build: ./django-chunked-upload
    ports:
      - "8000:8000"
    volumes:
      - ./django-chunked-upload/core/media:/app/media
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*

  frontend:
    build: ./react-chunked-upload
    ports:
      - "5173:5173"
    depends_on:
      - backend
